### ISSUE TITLE
UI.Window Dimensions seem to be off 

### ISSUE THREAD

**Issue by ShahFragcolor** [fragcolor-xyz/shards#481]
![image.png](https://images.zenhubusercontent.com/624187ee0cf085ebe2d9639f/0112e658-7a3c-47b1-adc3-12c5c929a18d)

- The width and height of the window has been set to 1920 by 1080

![image.png](https://images.zenhubusercontent.com/624187ee0cf085ebe2d9639f/4f434c67-298a-4c38-b2da-dfc49a3af9f3)
- But for some reason it seemslike the edges of the screen are at -600 and 600.  So the width of the screen appears only to be 1200 and the height 600

https://images.zenhubusercontent.com/214938881/1f655d6c-5a51-4441-98d7-05454cb12e98/mainwindow_2022_12_09_17_45_23.mp4

**Comment by guusw** [comment]
Yeah it might set actual window size instead of the size of the draw area size. Can fix that I think

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/481?planning-poker) with Zenhub @Kryptos-FR @sinkingsugar @tdbe

**Comment by guusw** [comment]
It seems to be correct for me, but maybe display scaling settings have an effect on the size
<img width="1096" alt="Region" src="https://user-images.githubusercontent.com/16842774/210384101-8e742a4a-bf1a-4f0a-b23c-2762e2ed72ec.PNG">

**Comment by guusw** [comment]
Oh yeah I forgot the UI does not necessarily use the same resolution as the window, since the window size is in pixels and the UI might be smaller if you display scaling is set to >100%

It's intended for the UI since otherwise it'd be hard to read and too small on high resolution screens. You'd either have to adjust your game based on scaling or better we can switch to using GFX shards and just use an orthographic camera with a fixed size
